deployment:
tasks:
  - export REPOPATH=/home/xingmojn/repositories/candy-machine-v2-responsive-ui* 
  - export SITEPATH=/home/xingmojn/public_html/
  - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH